// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: raft.proto

package raftrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Raft_AppendEntriesInRaft_FullMethodName = "/Raft/AppendEntriesInRaft"
	Raft_HeartbeatInRaft_FullMethodName     = "/Raft/HeartbeatInRaft"
	Raft_RequestVote_FullMethodName         = "/Raft/RequestVote"
)

// RaftClient is the client API for Raft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaftClient interface {
	AppendEntriesInRaft(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AppendEntriesInRaftRequest, AppendEntriesInRaftResponse], error)
	HeartbeatInRaft(ctx context.Context, in *AppendEntriesInRaftRequest, opts ...grpc.CallOption) (*AppendEntriesInRaftResponse, error)
	RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error)
}

type raftClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftClient(cc grpc.ClientConnInterface) RaftClient {
	return &raftClient{cc}
}

func (c *raftClient) AppendEntriesInRaft(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AppendEntriesInRaftRequest, AppendEntriesInRaftResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Raft_ServiceDesc.Streams[0], Raft_AppendEntriesInRaft_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AppendEntriesInRaftRequest, AppendEntriesInRaftResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Raft_AppendEntriesInRaftClient = grpc.BidiStreamingClient[AppendEntriesInRaftRequest, AppendEntriesInRaftResponse]

func (c *raftClient) HeartbeatInRaft(ctx context.Context, in *AppendEntriesInRaftRequest, opts ...grpc.CallOption) (*AppendEntriesInRaftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendEntriesInRaftResponse)
	err := c.cc.Invoke(ctx, Raft_HeartbeatInRaft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestVoteResponse)
	err := c.cc.Invoke(ctx, Raft_RequestVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftServer is the server API for Raft service.
// All implementations must embed UnimplementedRaftServer
// for forward compatibility.
type RaftServer interface {
	AppendEntriesInRaft(grpc.BidiStreamingServer[AppendEntriesInRaftRequest, AppendEntriesInRaftResponse]) error
	HeartbeatInRaft(context.Context, *AppendEntriesInRaftRequest) (*AppendEntriesInRaftResponse, error)
	RequestVote(context.Context, *RequestVoteRequest) (*RequestVoteResponse, error)
	mustEmbedUnimplementedRaftServer()
}

// UnimplementedRaftServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRaftServer struct{}

func (UnimplementedRaftServer) AppendEntriesInRaft(grpc.BidiStreamingServer[AppendEntriesInRaftRequest, AppendEntriesInRaftResponse]) error {
	return status.Errorf(codes.Unimplemented, "method AppendEntriesInRaft not implemented")
}
func (UnimplementedRaftServer) HeartbeatInRaft(context.Context, *AppendEntriesInRaftRequest) (*AppendEntriesInRaftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartbeatInRaft not implemented")
}
func (UnimplementedRaftServer) RequestVote(context.Context, *RequestVoteRequest) (*RequestVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestVote not implemented")
}
func (UnimplementedRaftServer) mustEmbedUnimplementedRaftServer() {}
func (UnimplementedRaftServer) testEmbeddedByValue()              {}

// UnsafeRaftServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftServer will
// result in compilation errors.
type UnsafeRaftServer interface {
	mustEmbedUnimplementedRaftServer()
}

func RegisterRaftServer(s grpc.ServiceRegistrar, srv RaftServer) {
	// If the following call pancis, it indicates UnimplementedRaftServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Raft_ServiceDesc, srv)
}

func _Raft_AppendEntriesInRaft_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RaftServer).AppendEntriesInRaft(&grpc.GenericServerStream[AppendEntriesInRaftRequest, AppendEntriesInRaftResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Raft_AppendEntriesInRaftServer = grpc.BidiStreamingServer[AppendEntriesInRaftRequest, AppendEntriesInRaftResponse]

func _Raft_HeartbeatInRaft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesInRaftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).HeartbeatInRaft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raft_HeartbeatInRaft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).HeartbeatInRaft(ctx, req.(*AppendEntriesInRaftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Raft_RequestVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).RequestVote(ctx, req.(*RequestVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Raft_ServiceDesc is the grpc.ServiceDesc for Raft service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Raft_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Raft",
	HandlerType: (*RaftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HeartbeatInRaft",
			Handler:    _Raft_HeartbeatInRaft_Handler,
		},
		{
			MethodName: "RequestVote",
			Handler:    _Raft_RequestVote_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AppendEntriesInRaft",
			Handler:       _Raft_AppendEntriesInRaft_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "raft.proto",
}
